### ISSUE TITLE
type selection is empty

### ISSUE THREAD

**Issue by faxm0dem** [anthonygalea/riemann-console#2]
For some reason the type selection dialog is empty.
Missing font on my system?
![2019-09-24-094059_6400x2160_scrot](https://user-images.githubusercontent.com/112638/65491956-5c8f0d00-deb0-11e9-9e18-8035a794e692.png)

**Comment by anthonygalea** [comment]
I don't think so. I only tested on safari and chrome so far. I'm guessing you're on firefox because that's where I could reproduce it. Can you try again after pulling latest?

**Comment by anthonygalea** [comment]
Sorry Fabien just realised I accidentally closed this issue with my last commit. If it doesn't resolve the problem let me know.

**Comment by faxm0dem** [comment]
Yeah ff it is. I'll try tomorrow, thanks!

**Comment by faxm0dem** [comment]
your change fixed it! thanks!
